[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux"
startup_command = "v tmux.conf.sh"
preview_command = "bat --color=always ~/dotfiles/tmux/tmux.conf.sh"

[[session]]
name = "sesh config"
path = "~/dotfiles/sesh"
startup_command = "v sesh.toml"
preview_command = "bat --color=always ~/dotfiles/sesh/.config/sesh/sesh.toml"

[[session]]
name = "zshrc config"
path = "~/dotfiles/zsh"
startup_command = "v zshrc.sh"
preview_command = "bat --color=always ~/dotfiles/zshrc/.config"

[[session]]
name = "neovim keymaps"
path = "~/.config/nvim/lua/config/keymaps.lua"
startup_command = "v keymaps.lua"
preview_command = "bat --color=always ~/dotfiles/neovim/neobean/lua/config/keymaps.lua"

